[package]
name = "my_first_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1.12"
regex = "0.1.41"
rand = "0.8.3"
dialoguer = "0.10.0"
